# CPack settings for NeuroScope: DEB on Linux, NSIS/ZIP on Windows, DMG on macOS.
set(CPACK_PACKAGE_NAME "neuroscope")
set(CPACK_PACKAGE_VENDOR "Neurosuite")
set(CPACK_PACKAGE_CONTACT "Florian Franzen <FlorianFranzen@gmail.com>")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${PROJECT_DESCRIPTION}")
set(CPACK_PACKAGE_DESCRIPTION_FILE "${PROJECT_SOURCE_DIR}/cpack/description")
set(CPACK_PACKAGE_HOMEPAGE_URL "${PROJECT_HOMEPAGE_URL}")
set(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/LICENSE")
set(CPACK_PACKAGE_EXECUTABLES "neuroscope" "NeuroScope")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "NeuroScope")

if(WIN32)
    set(CPACK_GENERATOR "NSIS;ZIP")
    set(CPACK_NSIS_PACKAGE_NAME "NeuroScope")
    set(CPACK_NSIS_DISPLAY_NAME "NeuroScope ${PROJECT_VERSION}")
    set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
    set(CPACK_NSIS_URL_INFO_ABOUT "${PROJECT_HOMEPAGE_URL}")
    set(CPACK_NSIS_HELP_LINK "https://github.com/neurosuite/neuroscope/issues")
    set(CPACK_NSIS_INSTALLED_ICON_NAME "bin\\\\neuroscope.exe")
    set(CPACK_NSIS_MUI_ICON "${PROJECT_SOURCE_DIR}/src/neuroscope.ico")
    set(CPACK_SYSTEM_NAME "win64")
elseif(APPLE)
    set(CPACK_GENERATOR "DragNDrop")
    # The GPL needs no click-through agreement; it also blocks unattended mounting.
    set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE OFF)
    set(CPACK_DMG_FORMAT "UDBZ")
    set(CPACK_SYSTEM_NAME "macos-${CMAKE_SYSTEM_PROCESSOR}")
else()
    set(CPACK_GENERATOR "DEB")
    set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
    set(CPACK_DEBIAN_PACKAGE_SECTION "science")
    set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
    # A bundled libneurosuite lives in this package's lib dir.
    set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS_PRIVATE_DIRS "${CMAKE_BINARY_DIR}/_deps/neurosuite-build/src")
    set(CPACK_DEBIAN_PACKAGE_SUGGESTS "klusters, ndmanager, neurosuite-mime")
    set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA
        "${PROJECT_SOURCE_DIR}/cpack/postinst;${PROJECT_SOURCE_DIR}/cpack/postrm")
endif()

include(CPack)
