#!/bin/bash

source ./version
start=$(pwd)

(
	cd ..
	ln -s $start/description-pak .

	# Package
	sudo checkinstall --maintainer 'Michael Zugaro' --pkgname $name --pkgversion $version --pkgrelease $release --pkglicense GPL --pkggroup Scientific --pkgsource $source

	rm description-pak

	# Install?
	if [ "$1" == '-i' ]
	then
		arch=i386
		[ -z "$(uname -a | grep x86_64)" ] || arch=amd64
		sudo dpkg --force-overwrite -i ${name}_$version-${release}_$arch.deb
	fi
)
