#!/bin/bash

source ./version
start=$(pwd)

# Package name
distribution=$(lsb_release -si|tr [:upper:] [:lower:])
release=$(lsb_release -cs)
if [ "$(uname -i | grep x86_64)" == "x86_64" ]
then
	x86=true
else
	x86=false
fi
case $distribution in
	debian|ubuntu)
		$x86 && arch=amd64 || arch=i386
		package=${name}_$version-${release}_$arch.deb
		output=-D
		# Use 'depends' to get a wild guess
		requires="libaudio2, libc6, libexpat1, libffi6, libfontconfig1, libfreetype6, libgcc1, libglib2.0-0, libgstreamer0.10-0, libgstreamer-plugins-base0.10-0, libice6, libklustersshared, liborc-0.4-0, libpcre3, libpng12-0, libqt4-network, libqt4-xml, libqtcore4, libqtgui4, libqtwebkit4, libsm6, libsqlite3-0, libstdc++6, libuuid1, libx11-6, libxau6, libxcb1, libxdmcp6, libxext6, libxi6, libxml2, libxrender1, libxt6, zlib1g"
		;;
	opensuse)
		$x86 && arch=x86_64 || arch=i586
		package=$name-$version-$release.$arch.rpm
		output=-R
		# Adapt 'depends' to get a wild guess
		requires=libklustersshared
		;;
	fedora)
		$x86 && arch=x86_64 || arch=i686
		package=$name-$version-$release.$arch.rpm
		output=-R
		# Adapt 'depends' to get a wild guess
		requires=libklustersshared
		;;
	*)
		echo "Unknown distribution '$distribution'"
		exit 1
		;;
esac

# Website
source=http://$name.sourceforge.net

(
	cd ../build
	ln -s $start/description-pak .

	# Package
	sudo checkinstall $output --maintainer 'Michael Zugaro' --pkgname $name --pkgversion $version --pkgrelease $release --pkglicense GPL --pkggroup Scientific --pkgsource $source --pkgarch $arch --requires "$requires" --pakdir $start --delspec

	rm description-pak
)
