#!/bin/bash

source ./version

(
	echo "***********************************************************************************"
	echo "  Cleaning (removing object files and executables)"
	echo "***********************************************************************************"
	cd ..
	make clean

	echo "***********************************************************************************"
	echo "  Archiving"
	echo "***********************************************************************************"

	dir=$(basename $(pwd))
	cd ..
	sudo tar -cvz --exclude $dir/${name}_$version.tar.gz -f $dir/${name}_$version.tar.gz $dir
)