#!/bin/bash

source ./version

# Tarball name
tarball=${name}_$version.tar.gz

(
	cd ..
	dir=$(basename $(pwd))
	cd ..
	sudo tar -cvz --exclude '*.tar.gz' --exclude '.git*' --exclude $dir/build --exclude '*deb' -f $dir/package/${name}_$version.tar.gz $dir
)
