#!/bin/bash

source ./version

BASE=/home/install/CMBN
PACKAGES=$BASE/packages
SOURCES=$BASE/sources
OLD_BASE=$BASE/old
OLD_PACKAGES=$OLD_BASE/packages
OLD_SOURCES=$OLD_BASE/sources

tarball=../${name}_$version.tar.gz
i386=../${name}_$version-${release}_i386.deb
amd64=../${name}_$version-${release}_amd64.deb

# Store new tarball, and move old version to 'archive'
if [ -f $tarball ]
then
	sudo mv -v $SOURCES/${name}*gz $OLD_SOURCES
	sudo mv -v $tarball $SOURCES
fi

# Store new 64bit package, and move old version to 'archive'
if [ -f $amd64 ]
then
	sudo mv -v $PACKAGES/${name}*amd64*deb $OLD_PACKAGES
	sudo mv -v $amd64 $PACKAGES
fi

# Store new 32bit package, and move old version to 'archive'
if [ -f $i386 ]
then
	sudo mv -v $PACKAGES/${name}*i386*deb $OLD_PACKAGES
	sudo mv -v $i386 $PACKAGES
fi

